services:
  n8n-editor:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-zyndai:0.0.1
    container_name: n8n-zyndai
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_PUBLIC_API_BASE_URL=${N8N_PUBLIC_API_BASE_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_CUSTOM_EXTENSIONS=/home/node/n8n-custom-nodes
      # CRITICAL: Must match Dockerfile
      - NODE_PATH=/home/node/deps/node_modules
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: