services:
  n8n-editor:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-zyndai:0.0.1
    container_name: n8n-zyndai
    volumes: 
      - ./data_n8n:/home/node/.n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
